-- 01_app_user_ddl.sql

-- Switch to PDB only if needed
DECLARE
  v_con VARCHAR2(128) := SYS_CONTEXT('USERENV','CON_NAME');
BEGIN
  IF v_con = 'CDB$ROOT' THEN
    EXECUTE IMMEDIATE 'ALTER SESSION SET CONTAINER = FREEPDB1';
  END IF;
END;
/
ALTER SESSION SET CURRENT_SCHEMA = APP;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE APP_USER_TABLE1 PURGE';
  EXECUTE IMMEDIATE 'DROP TABLE APP_USER_TABLE2 PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE APP_USER_TABLE1 (
  OID     RAW(16)      NOT NULL,
  NAME    VARCHAR2(50) NOT NULL,
  ZIPCODE NUMBER(5)    NOT NULL,
  STATE   CHAR(2)      NOT NULL,
  CITY    VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_APP_USER_T1 PRIMARY KEY (OID)
);

CREATE TABLE ZIPCODE_SUMMARY1 (
    uuid     VARCHAR2(36),
    zipcode  VARCHAR2(10),
    cnt      NUMBER
);

CREATE TABLE APP_USER_TABLE2
AS SELECT * FROM APP_USER_TABLE1 WHERE 1=0;
ALTER TABLE APP_USER_TABLE2 ADD CONSTRAINT PK_APP_USER_T2 PRIMARY KEY (OID);

CREATE INDEX idx_user_state_zip 
ON APP_USER_TABLE2 (STATE, ZIPCODE);
